service: pp-api-tst

env:
  clear:
    PP_HST: '<%= ENV["PP_HOSTNAME_DB_TST"] %>'
    PP_USR: '<%= ENV["PP_USR_TST"] %>'

# Deploy to these servers.
servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_TST"] %>'
    options:
      publish:
        - '<%= ENV["PP_PORT_API_TST"] %>:<%= ENV["PP_PORT_API"] %>'

ssh:
  user: '<%= ENV["PP_USR_SSH_TST"] %>'

# dev: no TLS; unique proxy host to avoid conflicts with prod
proxy:
  host: test-api.pitchperfect.eu.com
  ssl: true
  app_port: <%= ENV["PP_PORT_API"] %>
  healthcheck:
    path: /health
    timeout: 10
    interval: 2

builder:
  arch: amd64
  remote: 'ssh://<%= ENV["PP_USR_SSH_TST"] %>@<%= ENV["PP_HOSTNAME_SSH_TST"] %>'
