service: pp-api-prd

env:
  clear:
    PP_HST: '<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'
    PP_USR: '<%= ENV["PP_USR_PRD"] %>'

# Deploy to these servers.
servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'
    options:
      publish:
        - '<%= ENV["PP_PORT_API_PRD"] %>:<%= ENV["PP_PORT_API"] %>'
ssh:
  user: '<%= ENV["PP_USR_SSH_PRD"] %>'

# dev: no TLS; unique proxy host to avoid conflicts with prod
proxy:
  host: api.pitchperfect.eu.com
  ssl: true
  app_port: <%= ENV["PP_PORT_API"] %>
  healthcheck:
    path: /health
    timeout: 10
    interval: 2

builder:
  arch: amd64
  remote: 'ssh://<%= ENV["PP_USR_SSH_PRD"] %>@<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'
